services:
  # Сервис Redis для синхронизации воркеров
  redis:
    image: redis:alpine
    container_name: redis_broker
    ports:
      - "6379:6379"
    restart: always

  # Наше FastAPI приложение
  app:
    build: .
    container_name: ws_service
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    # Настройка для Graceful Shutdown (ТЗ: ждать до 30 минут)
    stop_grace_period: 31m
    depends_on:
      - redis
    restart: always